version: '3.7'
services:
  tomoni-front:
    image: node
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: yarn && yarn dev
    environment:
      - HOST=0.0.0.0
    networks:
      - docker_default

networks:
  docker_default:
    external: true
    name: docker_default

